# Generated by Django 5.1.6 on 2025-02-27 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_administrator_delete_director_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
